version: "3"

tasks:
  01-build:
    desc: "Build the project"
    cmds:
      - echo "Building the project..."
      - go build -o app

  02-run:
    desc: "Run the application"
    cmds:
      - echo "Running the application..."
      - ./app
  